# ============================================================================
# Generates the ECDSA P-256 signing keypair for YADUA's auto-updater.
#
#   RUN THIS OFFLINE, ONCE. It:
#     * writes the PRIVATE key to <OutDir>\yadua-signing-key.pem
#       -> keep it OFFLINE. Set its full contents as the GitHub Actions secret
#          YADUA_SIGNING_KEY (used by the release signing step). Never commit it.
#     * overwrites src\update_pubkey.h with the matching PUBLIC key, which is
#       compiled into the binary and removes the "placeholder" guard so the
#       updater turns on.
#     * prints the public-key fingerprint to paste into README.md.
#
# Regenerating makes a NEW key: every previously released signature stops
# verifying, and users on old builds (which embed the old public key) will no
# longer accept new updates. Only do it intentionally (e.g. key compromise).
#
# Requires PowerShell 7+ (uses .NET's modern ECDsa PEM APIs).
# ============================================================================
param(
    [string]$OutDir = (Join-Path $PSScriptRoot '..\.keys')
)
$ErrorActionPreference = 'Stop'

if ($PSVersionTable.PSVersion.Major -lt 7) {
    throw "Run this in PowerShell 7+ (pwsh), not Windows PowerShell 5.x."
}

$pubHeader = Join-Path $PSScriptRoot '..\src\update_pubkey.h'
New-Item -ItemType Directory -Force $OutDir | Out-Null
$privPath = Join-Path $OutDir 'yadua-signing-key.pem'

if (Test-Path $privPath) {
    Write-Warning "A key already exists at $privPath."
    $ans = Read-Host "Overwrite and invalidate all existing signatures? (type YES)"
    if ($ans -ne 'YES') { Write-Host 'Aborted.'; return }
}

# --- generate -------------------------------------------------------------
$ec = [System.Security.Cryptography.ECDsa]::Create(
    [System.Security.Cryptography.ECCurve]::CreateFromFriendlyName('nistP256'))
$pub = $ec.ExportParameters($false)      # public point only
$X = $pub.Q.X                            # 32 bytes, big-endian
$Y = $pub.Q.Y

if ($X.Length -ne 32 -or $Y.Length -ne 32) {
    throw "Unexpected key size (X=$($X.Length) Y=$($Y.Length)); expected 32/32."
}

# fingerprint = SHA-256(X || Y)
$blob = New-Object byte[] 64
[Array]::Copy($X, 0, $blob, 0, 32)
[Array]::Copy($Y, 0, $blob, 32, 32)
$fp = ([System.Security.Cryptography.SHA256]::Create().ComputeHash($blob) |
       ForEach-Object { $_.ToString('x2') }) -join ''

# --- write private key (offline) ------------------------------------------
$ec.ExportPkcs8PrivateKeyPem() | Set-Content -Path $privPath -Encoding ascii -NoNewline

# --- write the embedded public-key header ---------------------------------
function CArray([byte[]]$b) { ($b | ForEach-Object { '0x{0:x2}' -f $_ }) -join ', ' }

$header = @"
// ============================================================================
// Embedded ECDSA P-256 PUBLIC key for verifying signed update manifests.
//
// GENERATED by tools/gen-signing-key.ps1 - do not edit by hand. Only the
// public half lives here; the private half stays offline and signs releases.
//
// Format: the raw P-256 public point, X then Y, 32 bytes each (big-endian),
// exactly the bytes BCRYPT_ECCPUBLIC_BLOB expects after its 8-byte header.
// ============================================================================
#pragma once

static const unsigned char kYaduaUpdatePubKeyX[32] = { $(CArray $X) };
static const unsigned char kYaduaUpdatePubKeyY[32] = { $(CArray $Y) };

// SHA-256 of (X || Y), lowercase hex - shown in About; publish it in README.
#define YADUA_UPDATE_PUBKEY_FINGERPRINT \
    "$fp"
"@
Set-Content -Path $pubHeader -Value $header -Encoding ascii

Write-Host ""
Write-Host "Public key embedded in src\update_pubkey.h (placeholder removed)."
Write-Host "Private key written to: $privPath  (KEEP OFFLINE, do not commit)"
Write-Host ""
Write-Host "Key fingerprint (SHA-256 of X||Y):"
Write-Host "  $fp"
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Set the GitHub Actions secret YADUA_SIGNING_KEY to the full"
Write-Host "     contents of $privPath (Settings > Secrets and variables > Actions)."
Write-Host "  2. Commit src\update_pubkey.h and paste the fingerprint into README.md."
Write-Host "  3. Delete or vault the .pem once the secret is set; never commit it."
